server:
  port: 34101
spring:
  application:
    name: vlp-auth-service
  datasource:
    url: jdbc:h2:mem:auth-db
    username: vlp
    password: vlp
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
management:
  server:
    port: 44101